//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpContact { get; set; }
        public string Designation { get; set; }
        public string Salary { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string Password { get; set; }
        public int Status { get; set; }
    }
}
