//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells_Details
    {
        public string SellsDetailsId { get; set; }
        public string SellsId { get; set; }
        public string ProductId { get; set; }
        public string SellsQuentity { get; set; }
        public string SellsPrice { get; set; }
        public string Amount { get; set; }
    
        public virtual Sell Sell { get; set; }
    }
}
